# Server port (We will use 8080 for this project)
server.port=8084

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/nexusadmin_db
spring.datasource.username=postgres
spring.datasource.password=S3rg1024!

# Hibernate Configuration (Creates tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT CONFIGURATION ---
# This key is a random text in Base64 (Minimum 256 bits of security).
# In a real job, this goes in the .env, not in the code! But for now we leave it here.
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token duration in milliseconds (86400000 ms = 24 hours)
application.security.jwt.expiration=86400000